[terminal.shell]
program = "nu"
args = []

[window]
dimensions = { columns = 135, lines = 35 }

[font]
normal = { family = "MesloLGL Nerd Font Mono" }
size = 8

[cursor]
style = { shape = "Beam", blinking = "On" }

[general]
import = [
	"themes/themes/dracula.toml"
]

[terminal]
