#[terminal.shell]
# program = "/opt/homebrew/bin/fish"
# program = "/opt/homebrew/bin/nu"
# args = []

[font]
normal = { family = "MesloLGL Nerd Font Mono" }

[cursor]
style = { shape = "Beam", blinking = "On" }

[general]
import = [
	"themes/themes/dracula.toml"
]

[terminal]
